import { NextResponse } from 'next/server';
import { db } from '@/lib/db';

// Seed test courses into the database
export async function POST() {
  try {
    const testCourses = [
      {
        title: 'The Complete JavaScript Course 2024: From Zero to Expert',
        slug: 'complete-javascript-course-2024',
        description: 'Learn JavaScript from scratch and build real-world projects. This comprehensive course covers everything you need to know about JavaScript, including ES6+, async programming, OOP, and more.',
        instructor: 'Jonas Schmedtmann',
        category: 'Web Development',
        imageUrl: 'https://img-b.udemycdn.com/course/480x270/695770_20d8.jpg',
        udemyUrl: 'https://www.udemy.com/course/the-complete-javascript-course/',
        source: 'udemyfreebies',
        rating: 4.7,
        studentsCount: 250000,
        originalPrice: '$84.99',
        language: 'English',
        duration: '69 hours',
        isPublished: true,
        telegramPosted: false,
      },
      {
        title: 'Machine Learning A-Z: AI, Python & R + ChatGPT',
        slug: 'machine-learning-a-z-ai-python-r',
        description: 'Learn to create Machine Learning Algorithms in Python and R from two Machine Learning experts. Code templates included.',
        instructor: 'Kirill Eremenko',
        category: 'Data Science',
        imageUrl: 'https://img-b.udemycdn.com/course/480x270/950390_a5e0.jpg',
        udemyUrl: 'https://www.udemy.com/course/machinelearning/',
        source: 'udemyfreebies',
        rating: 4.5,
        studentsCount: 180000,
        originalPrice: '$99.99',
        language: 'English',
        duration: '44 hours',
        isPublished: true,
        telegramPosted: false,
      },
      {
        title: 'React - The Complete Guide 2024 (incl. Next.js)',
        slug: 'react-the-complete-guide-2024-incl-nextjs',
        description: 'Dive deep into React, Redux, React-Router, Hooks, Next.js, and more! Build real-world apps with modern React.',
        instructor: 'Maximilian Schwarzmüller',
        category: 'Web Development',
        imageUrl: 'https://img-b.udemycdn.com/course/480x270/1706558_e596.jpg',
        udemyUrl: 'https://www.udemy.com/course/react-the-complete-guide-incl-redux/',
        source: 'studybullet',
        rating: 4.6,
        studentsCount: 320000,
        originalPrice: '$94.99',
        language: 'English',
        duration: '68 hours',
        isPublished: true,
        telegramPosted: false,
      },
      {
        title: 'Python for Data Science and Machine Learning Bootcamp',
        slug: 'python-for-data-science-machine-learning-bootcamp',
        description: 'Learn how to use NumPy, Pandas, Seaborn, Matplotlib, Plotly, Scikit-Learn, Machine Learning, Tensorflow, and more!',
        instructor: 'Jose Portilla',
        category: 'Python',
        imageUrl: 'https://img-b.udemycdn.com/course/480x270/589444_7a3c.jpg',
        udemyUrl: 'https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/',
        source: 'studybullet',
        rating: 4.6,
        studentsCount: 155000,
        originalPrice: '$89.99',
        language: 'English',
        duration: '25 hours',
        isPublished: true,
        telegramPosted: false,
      },
      {
        title: 'AWS Certified Solutions Architect - Associate 2024',
        slug: 'aws-certified-solutions-architect-associate-2024',
        description: 'Pass the AWS Solutions Architect - Associate Exam with hands-on labs and real-world scenarios.',
        instructor: 'Stephane Maarek',
        category: 'Cloud & DevOps',
        imageUrl: 'https://img-b.udemycdn.com/course/480x270/2823770_9839.jpg',
        udemyUrl: 'https://www.udemy.com/course/aws-certified-solutions-architect-associate/',
        source: 'udemyfreebies',
        rating: 4.7,
        studentsCount: 220000,
        originalPrice: '$79.99',
        language: 'English',
        duration: '28 hours',
        isPublished: true,
        telegramPosted: true,
      },
      {
        title: 'Flutter & Dart - The Complete Guide 2024',
        slug: 'flutter-dart-the-complete-guide-2024',
        description: 'Learn Flutter and Dart from scratch, build beautiful cross-platform apps for iOS and Android.',
        instructor: 'Maximilian Schwarzmüller',
        category: 'Mobile Development',
        imageUrl: 'https://img-b.udemycdn.com/course/480x270/2477890_6978.jpg',
        udemyUrl: 'https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/',
        source: 'studybullet',
        rating: 4.7,
        studentsCount: 195000,
        originalPrice: '$89.99',
        language: 'English',
        duration: '39 hours',
        isPublished: true,
        telegramPosted: true,
      },
      {
        title: 'Ethical Hacking Bootcamp - Learn Ethical Hacking',
        slug: 'ethical-hacking-bootcamp-learn-ethical-hacking',
        description: 'Learn ethical hacking and penetration testing with practical hands-on exercises.',
        instructor: 'Zaid Sabih',
        category: 'Cybersecurity',
        imageUrl: 'https://img-b.udemycdn.com/course/480x270/1570280_6dc0.jpg',
        udemyUrl: 'https://www.udemy.com/course/learn-ethical-hacking-from-scratch/',
        source: 'udemyfreebies',
        rating: 4.5,
        studentsCount: 85000,
        originalPrice: '$94.99',
        language: 'English',
        duration: '14 hours',
        isPublished: true,
        telegramPosted: false,
      },
      {
        title: 'UI/UX Design with Figma - Complete Course',
        slug: 'ui-ux-design-with-figma-complete-course',
        description: 'Master Figma for UI/UX design. Learn design thinking, wireframing, prototyping, and more.',
        instructor: 'Daniel Walter Scott',
        category: 'Design',
        imageUrl: 'https://img-b.udemycdn.com/course/480x270/4258220_e71e.jpg',
        udemyUrl: 'https://www.udemy.com/course/ui-ux-design-with-figma/',
        source: 'studybullet',
        rating: 4.4,
        studentsCount: 72000,
        originalPrice: '$74.99',
        language: 'English',
        duration: '16 hours',
        isPublished: true,
        telegramPosted: false,
      },
      {
        title: 'Digital Marketing Masterclass - 23 Courses in 1',
        slug: 'digital-marketing-masterclass-23-courses-in-1',
        description: 'Learn SEO, Social Media Marketing, Google Ads, Facebook Ads, Email Marketing, and more.',
        instructor: 'Phil Ebiner',
        category: 'Marketing',
        imageUrl: 'https://img-b.udemycdn.com/course/480x270/1793550_2f22.jpg',
        udemyUrl: 'https://www.udemy.com/course/the-complete-digital-marketing-course/',
        source: 'udemyfreebies',
        rating: 4.4,
        studentsCount: 130000,
        originalPrice: '$94.99',
        language: 'English',
        duration: '33 hours',
        isPublished: true,
        telegramPosted: false,
      },
      {
        title: 'The Complete Photography Masterclass',
        slug: 'the-complete-photography-masterclass',
        description: 'Learn photography from beginner to advanced. Master your camera, lighting, composition, and editing.',
        instructor: 'Phil Ebiner',
        category: 'Photography',
        imageUrl: 'https://img-b.udemycdn.com/course/480x270/5040964_b2fc.jpg',
        udemyUrl: 'https://www.udemy.com/course/photography-masterclass/',
        source: 'studybullet',
        rating: 4.6,
        studentsCount: 45000,
        originalPrice: '$69.99',
        language: 'English',
        duration: '22 hours',
        isPublished: true,
        telegramPosted: false,
      },
      {
        title: 'Docker & Kubernetes: The Practical Guide',
        slug: 'docker-kubernetes-the-practical-guide',
        description: 'Learn Docker and Kubernetes from scratch. Deploy containerized applications with confidence.',
        instructor: 'Maximilian Schwarzmüller',
        category: 'Cloud & DevOps',
        imageUrl: 'https://img-b.udemycdn.com/course/480x270/2655382_41d1.jpg',
        udemyUrl: 'https://www.udemy.com/course/docker-kubernetes-the-practical-guide/',
        source: 'udemyfreebies',
        rating: 4.7,
        studentsCount: 175000,
        originalPrice: '$84.99',
        language: 'English',
        duration: '21 hours',
        isPublished: true,
        telegramPosted: false,
      },
      {
        title: 'Excel VBA Programming & Macros - Complete Guide',
        slug: 'excel-vba-programming-macros-complete-guide',
        description: 'Master Excel VBA programming. Automate repetitive tasks and build powerful macros.',
        instructor: 'Kyle Pew',
        category: 'Business',
        imageUrl: 'https://img-b.udemycdn.com/course/480x270/989242_7bb9.jpg',
        udemyUrl: 'https://www.udemy.com/course/excel-vba-programming-macros/',
        source: 'studybullet',
        rating: 4.5,
        studentsCount: 65000,
        originalPrice: '$49.99',
        language: 'English',
        duration: '8 hours',
        isPublished: true,
        telegramPosted: false,
      },
    ];

    // Clear existing data
    await db.course.deleteMany({});

    // Insert test courses
    const result = await db.course.createMany({
      data: testCourses,
    });

    return NextResponse.json({
      success: true,
      message: `Seeded ${result.count} test courses`,
      count: result.count,
    });
  } catch (e) {
    return NextResponse.json({ error: String(e) }, { status: 500 });
  }
}
